## Lab Condivisi {.unnumbered}

I lab in questa sezione coprono argomenti e tecniche applicabili a diverse piattaforme hardware. Questi laboratori sono progettati per essere indipendenti da schede specifiche, consentendo di concentrarsi sui concetti fondamentali e sugli algoritmi utilizzati nelle applicazioni  (tiny) ML.

Esplorando questi "shared lab", si otterrà una comprensione più approfondita delle sfide e delle soluzioni comuni nell'apprendimento automatico embedded. Le conoscenze e le competenze acquisite qui saranno preziose indipendentemente dall'hardware specifico con cui lavorerà in futuro.

| Esercizio | Nicla Vision | XIAO ESP32S3 |
|:------------------------------|:--------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------|
| KWS Feature Engineering | ✔ [Link](./kws_feature_eng/kws_feature_eng.it.qmd) | ✔ [Link](./kws_feature_eng/kws_feature_eng.it.qmd) |
| Blocco delle Feature Spettrali DSP | ✔ [Link](./dsp_spectral_features_block/dsp_spectral_features_block.it.qmd) | ✔ [Link](./dsp_spectral_features_block/dsp_spectral_features_block.it.qmd) |

