---
comments: false
---

# Copyright {.unnumbered}

Questo libro è open source e sviluppato in modo collaborativo tramite GitHub. Salvo diversa indicazione, questo lavoro è concesso in licenza con Creative Commons Attribuzione-Non commerciale-Condividi allo stesso modo 4.0 Internazionale (CC BY-NC-SA 4.0 CC BY-SA 4.0). Il testo completo della licenza si trova [qui](https://creativecommons.org/licenses/by-nc-sa/4.0).

I collaboratori di questo progetto hanno dedicato i loro contributi al pubblico dominio o con la stessa licenza aperta del progetto originale. Sebbene i contributi siano collaborativi, ogni collaboratore mantiene il copyright sui rispettivi contributi.

Per i dettagli sulla paternità, i contributi e come contribuire, consultare il repository del progetto su [GitHub](https://github.com/harvard-edge/cs249r_book).

Tutti i marchi e i marchi registrati menzionati in questo libro sono di proprietà dei rispettivi proprietari.

Le informazioni fornite in questo libro sono ritenute accurate e affidabili. Tuttavia, gli autori, i curatori e gli editori non possono essere ritenuti responsabili per eventuali danni causati o presumibilmente causati, direttamente o indirettamente, dalle informazioni contenute nel presente libro.
