# Dataset {#sec-datasets}

1. **Google Speech Commands Dataset**
   - Descrizione: Un set di file audio .wav da un secondo, ciascuno contenente una singola parola inglese parlata.
   - [Link al Dataset](https://ai.googleblog.com/2017/08/launching-speech-commands-dataset.html)

2. **VisualWakeWords Dataset**
   - Descrizione: Un dataset su misura per applicazioni di visione TinyML, costituito da immagini etichettate binarie che indicano se una persona è presente o meno nell'immagine.
   - [Link al Dataset](https://github.com/tensorflow/models/tree/master/research/slim#preparing-the-visualwakewords-dataset)

3. **EMNIST Dataset**
   - Descrizione: Un dataset contenente immagini da 28x28 pixel di caratteri e cifre scritti a mano, che è un'estensione del dataset MNIST ma include lettere.
   - [Link al Dataset](https://www.nist.gov/itl/products-and-services/emnist-dataset)

4. **UCI Machine Learning Repository: Human Activity Recognition Using Smartphones**
   - Descrizione: Un dataset con le registrazioni di 30 partecipanti allo studio che svolgono "activities of daily living (ADL)" [attività quotidiane ] mentre trasportano uno smartphone montato sulla vita con sensori inerziali embedded.
   - [Link al Dataset](https://archive.ics.uci.edu/ml/datasets/human+activity+recognition+using+smartphones)

5. **PlantVillage Dataset**
   - Descrizione: Un dataset composto da immagini di foglie di colture sane e malate, categorizzate in base al tipo di coltura e al tipo di malattia, che potrebbe essere utilizzato in un progetto agricolo TinyML.
   - [Link al Dataset](https://github.com/spMohanty/PlantVillage-Dataset)

6. **Gesture Recognition using 3D Motion Sensing (3D Gesture Database)**
   - Descrizione: Questo dataset contiene dati sui gesti 3D registrati tramite un Leap Motion Controller, che potrebbe essere utile per progetti di riconoscimento dei gesti.
   - [Link al Dataset](https://lttm.dei.unipd.it/downloads/gesture/)

7. **Multilingual Spoken Words Corpus**
   - Descrizione: Un dataset contenente registrazioni di parole parlate comuni in varie lingue, utile per progetti di riconoscimento vocale mirati a più lingue.
   - [Link al Dataset](https://mlcommons.org/en/multilingual-spoken-words/)

8. **Wake Vision**
   - Descrizione: Un dataset contenente oltre 6 milioni di immagini per la classificazione binaria delle persone. Inoltre, include una suite di benchmark a grana fine per valutare l'equità e la robustezza dei modelli.
   - [Link al Dataset](https://wakevision.ai/)

Ricordarsi di verificare la licenza o i termini di utilizzo del dataset per essere sicuri che possa essere utilizzato per lo scopo previsto.
