# Prefazione {.unnumbered}

Benvenuti in {{< var title.long >}}. Questo libro è la porta d'accesso al mondo frenetico dei sistemi di intelligenza artificiale. È un'estensione del corso [CS249r](https://sites.google.com/g.harvard.edu/cs249-tinyml-2023) alla Harvard University.

```{=html}
<iframe src="github-button.html"></iframe>
```

Vogliamo rendere questo libro open source un lavoro collaborativo che riunisca spunti di studenti, professionisti e la più ampia comunità di professionisti dell'intelligenza artificiale. Vogliamo creare una guida completa che approfondisca i dettagli dei sistemi di intelligenza artificiale e le loro numerose applicazioni.

> "Se vuoi andare veloce, vai da solo. Se vuoi andare lontano, vai insieme ad altre persone".
> -- Proverbio africano

Questo non è un libro statico; è un documento vivo e pulsante. Lo stiamo rendendo open source e lo aggiorniamo costantemente per soddisfare le esigenze in continua evoluzione di questo campo dinamico. Contiene un ricco mix di conoscenze specialistiche che guideranno attraverso la complessa interazione tra algoritmi all'avanguardia e i principi fondamentali che li fanno funzionare. Stiamo preparando il terreno per il prossimo grande balzo nell'innovazione dell'IA.

# Perché Abbiamo Scritto Questo Libro

Viviamo in un'epoca in cui la tecnologia è in continua evoluzione. La collaborazione aperta e la condivisione delle conoscenze sono gli elementi costitutivi della vera innovazione. Questo è lo spirito alla base di questo lavoro. Andiamo oltre il tradizionale modello di libro di testo per creare un hub di conoscenza vivo, in modo che possiamo tutti condividere e imparare gli uni dagli altri.

Il libro si concentra sui principi e sui casi di studio dei sistemi di IA, con l'obiettivo di fornire una comprensione approfondita che aiuterà a navigare nel panorama in continua evoluzione dei sistemi di IA. Mantenendolo "open source", non stiamo solo rendendo accessibile l'apprendimento, ma stiamo anche invitando nuove idee e miglioramenti continui. In breve, stiamo costruendo una comunità in cui la conoscenza è libera di crescere e illuminare la strada verso la tecnologia AI globale.

# Cosa c'è da Sapere

Per immergersi in questo libro, non si dev'essere un esperto di AI. Tutto ciò di cui c'è bisogno è una conoscenza di base dei concetti di informatica e la curiosità di esplorare su come funzionano i sistemi AI. È qui che avviene l'innovazione e una conoscenza di base della programmazione e delle strutture dati sarà la bussola.

# Convenzioni del Libro

Per i dettagli sulle convenzioni utilizzate in questo libro, consultare la sezione [Convenzioni](./contents/conventions.qmd).

# Dichiarazione di Trasparenza dei Contenuti

Questo libro è un progetto guidato dalla comunità, con contenuti generati da numerosi collaboratori nel tempo. Il processo di creazione dei contenuti potrebbe aver coinvolto vari strumenti di editing, tra cui la tecnologia AI generativa. In qualità di autore principale, editore e curatore, il Prof. Vijay Janapa Reddi mantiene la supervisione umana e la supervisione editoriale per garantire che il contenuto sia accurato e pertinente. Tuttavia, nessuno è perfetto, quindi potrebbero comunque esserci delle inesattezze. Apprezziamo molto i feedback e invitiamo a fornire correzioni e suggerimenti. Questo approccio collaborativo è fondamentale per migliorare e mantenere la qualità del contenuto e rendere le informazioni accessibili a livello globale.

# Per dare una mano

Se si è interessati a contribuire, le linee guida si trovano [qui](https://github.com/harvard-edge/cs249r_book/blob/dev/contribute.md).

# Contatti

Ci sono domande o feedback? Si è liberi di inviare una [e-mail al Prof. Vijay Janapa Reddi]({{< var email.info >}}) direttamente, oppure si può [avviare un thread di discussione](https://github.com/harvard-edge/cs249r_book/discussions) su GitHub.

# Collaboratori

Un grande ringraziamento a tutti coloro che hanno contribuito a rendere questo libro quello che è! L'elenco completo dei singoli collaboratori è [qui](./contents/contributors.qmd) e ulteriori dettagli sullo stile GitHub [qui](https://github.com/harvard-edge/cs249r_book/graphs/contributors). Benvenuti come collaboratori!