
# Prefazione {.unnumbered}

Benvenuti in {{< var title.long >}}. Questo libro è la porta d'accesso al mondo frenetico dei sistemi di intelligenza artificiale. È un'estensione del corso [CS249r](https://sites.google.com/g.harvard.edu/cs249-tinyml-2023) alla Harvard University.

```{=html}
<iframe src="github-button.html"></iframe>
```

Abbiamo creato questo libro open source come sforzo collaborativo per riunire spunti di studenti, professionisti e la più ampia comunità di professionisti dell'IA. Il nostro obiettivo è sviluppare una guida completa che esplori le complessità dei sistemi di intelligenza artificiale e le loro numerose applicazioni.

> "Se vuoi andare veloce, vai da solo. Se vuoi andare lontano, vai insieme ad altre persone".
> -- Proverbio africano

Questo non è un libro statico; è un documento vivo e pulsante. Lo stiamo rendendo open source e lo aggiorniamo costantemente per soddisfare le esigenze in continua evoluzione di questo campo dinamico. Contiene un ricco mix di conoscenze specialistiche che guideranno attraverso la complessa interazione tra algoritmi all'avanguardia e i principi fondamentali che li fanno funzionare. Stiamo preparando il terreno per il prossimo grande balzo nell'innovazione dell'IA.

## Perché Abbiamo Scritto Questo Libro

Viviamo in un'epoca in cui la tecnologia è in continua evoluzione. La collaborazione aperta e la condivisione delle conoscenze sono gli elementi costitutivi della vera innovazione. Questo è lo spirito alla base di questo lavoro. Andiamo oltre il tradizionale modello di libro di testo per creare un hub di conoscenza vivo, in modo che possiamo tutti condividere e imparare gli uni dagli altri.

Il libro si concentra sui principi e sui casi di studio dei sistemi di IA, con l'obiettivo di fornire una comprensione approfondita che aiuterà a navigare nel panorama in continua evoluzione dei sistemi di IA. Mantenendolo "open source", non stiamo solo rendendo accessibile l'apprendimento, ma stiamo anche invitando nuove idee e miglioramenti continui. In breve, stiamo costruendo una comunità in cui la conoscenza è libera di crescere e illuminare la strada verso la tecnologia AI globale.

## Cosa c'è da Sapere

Per immergersi in questo libro, non si dev'essere un esperto di AI. Tutto ciò di cui c'è bisogno è una conoscenza di base dei concetti di informatica e la curiosità di esplorare su come funzionano i sistemi AI. È qui che avviene l'innovazione e una conoscenza di base della programmazione e delle strutture dati sarà la bussola.

## Dichiarazione di Trasparenza dei Contenuti

Questo libro è un progetto guidato dalla comunità, con contenuti generati da numerosi collaboratori nel tempo. Il processo di creazione dei contenuti potrebbe aver coinvolto vari strumenti di editing, tra cui la tecnologia AI generativa. In qualità di autore principale, editore e curatore, il Prof. Vijay Janapa Reddi mantiene la supervisione umana e la supervisione editoriale per garantire che il contenuto sia accurato e pertinente. Tuttavia, nessuno è perfetto, quindi potrebbero comunque esserci delle inesattezze. Apprezziamo molto i feedback e invitiamo a fornire correzioni e suggerimenti. Questo approccio collaborativo è fondamentale per migliorare e mantenere la qualità del contenuto e rendere le informazioni accessibili a livello globale.

## Per dare una mano

Se si è interessati a contribuire, le linee guida si trovano [qui](https://github.com/harvard-edge/cs249r_book/blob/dev/contribute.md).

## Contatti

Ci sono domande o feedback? Si è liberi di inviare una [e-mail al Prof. Vijay Janapa Reddi]({{< var email.info >}}) direttamente, oppure si può [avviare un thread di discussione](https://github.com/harvard-edge/cs249r_book/discussions) su GitHub.

## Collaboratori

Un grande ringraziamento a tutti coloro che hanno contribuito a rendere questo libro quello che è! L'elenco completo dei singoli collaboratori è [qui](contents/core/acknowledgements/acknowledgements.it.qmd) e ulteriori dettagli sullo stile GitHub [qui](https://github.com/harvard-edge/cs249r_book/graphs/contributors). Benvenuti come collaboratori!

## Copyright

Questo libro è open source e sviluppato in modo collaborativo tramite GitHub. Salvo diversa indicazione, questo lavoro è concesso in licenza con Creative Commons Attribuzione-Non commerciale-Condividi allo stesso modo 4.0 Internazionale (CC BY-NC-SA 4.0 CC BY-SA 4.0). Il testo completo della licenza si trova [qui](https://creativecommons.org/licenses/by-nc-sa/4.0).

I collaboratori di questo progetto hanno dedicato i loro contributi al pubblico dominio o con la stessa licenza aperta del progetto originale. Sebbene i contributi siano collaborativi, ogni collaboratore mantiene il copyright sui rispettivi contributi.

Per i dettagli sulla paternità, i contributi e come contribuire, consultare il repository del progetto su [GitHub](https://github.com/harvard-edge/cs249r_book).

Tutti i marchi e i marchi registrati menzionati in questo libro sono di proprietà dei rispettivi proprietari.

Le informazioni fornite in questo libro sono ritenute accurate e affidabili. Tuttavia, gli autori, i curatori e gli editori non possono essere ritenuti responsabili per eventuali danni causati o presumibilmente causati, direttamente o indirettamente, dalle informazioni contenute nel presente libro.
