git clone https://github.com/harvard-edge/cs249r_book.git
cd cs249r_book
Echo "Rendering English Version in '_book'"
quarto render

rename _quarto.yml _quarto_org.yml
rename index.qmd   index_org.qmd

copy "..\cs249r_book_it\_quarto.yml"                                                                              "."
copy "..\cs249r_book_it\index.qmd"                                                                                "."
copy "..\cs249r_book_it\references.it.qmd"                                                                        "."
copy "..\cs249r_book_it\Italian-reference-doc.docx"                                                               "."

copy "..\cs249r_book_it\contents\dedication.it.qmd"                                                               ".\contents\"
copy "..\cs249r_book_it\contents\contributors.it.qmd"                                                             ".\contents\"
copy "..\cs249r_book_it\contents\copyright.it.qmd"                                                                ".\contents\"
copy "..\cs249r_book_it\contents\about.it.qmd"                                                                    ".\contents\"
copy "..\cs249r_book_it\contents\acknowledgements\acknowledgements.it.qmd"                                        ".\contents\acknowledgements\"
copy "..\cs249r_book_it\contents\introduction\introduction.it.qmd"                                                ".\contents\introduction\"
copy "..\cs249r_book_it\contents\ml_systems\ml_systems.it.qmd"                                                    ".\contents\ml_systems\"
copy "..\cs249r_book_it\contents\dl_primer\dl_primer.it.qmd"                                                      ".\contents\dl_primer\"
copy "..\cs249r_book_it\contents\workflow\workflow.it.qmd"                                                        ".\contents\workflow\"
copy "..\cs249r_book_it\contents\data_engineering\data_engineering.it.qmd"                                        ".\contents\data_engineering\"
copy "..\cs249r_book_it\contents\frameworks\frameworks.it.qmd"                                                    ".\contents\frameworks\"
copy "..\cs249r_book_it\contents\training\training.it.qmd"                                                        ".\contents\training\"
copy "..\cs249r_book_it\contents\efficient_ai\efficient_ai.it.qmd"                                                ".\contents\efficient_ai\"
copy "..\cs249r_book_it\contents\optimizations\optimizations.it.qmd"                                              ".\contents\optimizations\"
copy "..\cs249r_book_it\contents\hw_acceleration\hw_acceleration.it.qmd"                                          ".\contents\hw_acceleration\"
copy "..\cs249r_book_it\contents\benchmarking\benchmarking.it.qmd"                                                ".\contents\benchmarking\"
copy "..\cs249r_book_it\contents\ondevice_learning\ondevice_learning.it.qmd"                                      ".\contents\ondevice_learning\"
copy "..\cs249r_book_it\contents\ops\ops.it.qmd"                                                                  ".\contents\ops\"
copy "..\cs249r_book_it\contents\privacy_security\privacy_security.it.qmd"                                        ".\contents\privacy_security\"
copy "..\cs249r_book_it\contents\responsible_ai\responsible_ai.it.qmd"                                            ".\contents\responsible_ai\"
copy "..\cs249r_book_it\contents\sustainable_ai\sustainable_ai.it.qmd"                                            ".\contents\sustainable_ai\"
copy "..\cs249r_book_it\contents\robust_ai\robust_ai.it.qmd"                                                      ".\contents\robust_ai\"
copy "..\cs249r_book_it\contents\generative_ai\generative_ai.it.qmd"                                              ".\contents\generative_ai\"
copy "..\cs249r_book_it\contents\ai_for_good\ai_for_good.it.qmd"                                                  ".\contents\ai_for_good\"
copy "..\cs249r_book_it\contents\conclusion\conclusion.it.qmd"                                                    ".\contents\conclusion\"
copy "..\cs249r_book_it\contents\labs\labs.it.qmd"                                                                ".\contents\labs\"
copy "..\cs249r_book_it\contents\labs\getting_started.it.qmd"                                                     ".\contents\labs\"
copy "..\cs249r_book_it\contents\labs\arduino\nicla_vision\nicla_vision.it.qmd"                                   ".\contents\labs\arduino\nicla_vision\"
copy "..\cs249r_book_it\contents\labs\arduino\nicla_vision\setup\setup.it.qmd"                                    ".\contents\labs\arduino\nicla_vision\setup\"
copy "..\cs249r_book_it\contents\labs\arduino\nicla_vision\image_classification\image_classification.it.qmd"      ".\contents\labs\arduino\nicla_vision\image_classification\"
copy "..\cs249r_book_it\contents\labs\arduino\nicla_vision\object_detection\object_detection.it.qmd"              ".\contents\labs\arduino\nicla_vision\object_detection\"
copy "..\cs249r_book_it\contents\labs\arduino\nicla_vision\kws\kws.it.qmd"                                        ".\contents\labs\arduino\nicla_vision\kws\"
copy "..\cs249r_book_it\contents\labs\arduino\nicla_vision\motion_classification\motion_classification.it.qmd"    ".\contents\labs\arduino\nicla_vision\motion_classification\"
copy "..\cs249r_book_it\contents\labs\seeed\xiao_esp32s3\xiao_esp32s3.it.qmd"                                     ".\contents\labs\seeed\xiao_esp32s3\"
copy "..\cs249r_book_it\contents\labs\seeed\xiao_esp32s3\setup\setup.it.qmd"                                      ".\contents\labs\seeed\xiao_esp32s3\setup\"
copy "..\cs249r_book_it\contents\labs\seeed\xiao_esp32s3\image_classification\image_classification.it.qmd"        ".\contents\labs\seeed\xiao_esp32s3\image_classification\"
copy "..\cs249r_book_it\contents\labs\seeed\xiao_esp32s3\object_detection\object_detection.it.qmd"                ".\contents\labs\seeed\xiao_esp32s3\object_detection\"
copy "..\cs249r_book_it\contents\labs\seeed\xiao_esp32s3\kws\kws.it.qmd"                                          ".\contents\labs\seeed\xiao_esp32s3\kws\"
copy "..\cs249r_book_it\contents\labs\seeed\xiao_esp32s3\motion_classification\motion_classification.it.qmd"      ".\contents\labs\seeed\xiao_esp32s3\motion_classification\"
copy "..\cs249r_book_it\contents\labs\raspi\raspi.it.qmd"                                                         ".\contents\labs\raspi\"
copy "..\cs249r_book_it\contents\labs\raspi\setup\setup.it.qmd"                                                   ".\contents\labs\raspi\setup\"
copy "..\cs249r_book_it\contents\labs\raspi\image_classification\image_classification.it.qmd"                     ".\contents\labs\raspi\image_classification\"
copy "..\cs249r_book_it\contents\labs\raspi\object_detection\object_detection.it.qmd"                             ".\contents\labs\raspi\object_detection\"
copy "..\cs249r_book_it\contents\labs\raspi\llm\llm.it.qmd"                                                       ".\contents\labs\raspi\llm\"
copy "..\cs249r_book_it\contents\labs\shared\shared.it.qmd"                                                       ".\contents\labs\shared\"
copy "..\cs249r_book_it\contents\labs\shared\kws_feature_eng\kws_feature_eng.it.qmd"                              ".\contents\labs\shared\kws_feature_eng\"
copy "..\cs249r_book_it\contents\labs\shared\dsp_spectral_features_block\dsp_spectral_features_block.it.qmd"      ".\contents\labs\shared\dsp_spectral_features_block\"
copy "..\cs249r_book_it\contents\tools.it.qmd"                                                                    ".\contents\"
copy "..\cs249r_book_it\contents\zoo_datasets.it.qmd"                                                             ".\contents\"
copy "..\cs249r_book_it\contents\zoo_models.it.qmd"                                                               ".\contents\"
copy "..\cs249r_book_it\contents\learning_resources.it.qmd"                                                       ".\contents\"
copy "..\cs249r_book_it\contents\community.it.qmd"                                                                ".\contents\"
copy "..\cs249r_book_it\contents\case_studies.it.qmd"                                                             ".\contents\"
copy "..\cs249r_book_it\contents\conventions.it.qmd"                                                              ".\contents\"

Echo "Rendering della versione italiana in '_book_it'"
quarto render	